### PR TITLE
It seems you have to explicitly tell the client to use TLS

### PR DESCRIPTION
**Pull request by lukewestby**
This might be why we're seeing issues in staging but not locally

### CODE REVIEW

**Comment by stoeffel** [comment]
we should point this pr to the upstream repo and merge it into https://github.com/NoRedInk/servant-ruby/tree/next-version

**Review by stoeffel — APPROVED** [review]
Nice catch!

**Comment by stoeffel** [comment]
closed in favour of https://github.com/joneshf/servant-ruby/pull/18

**Comment by stoeffel** [comment]
also merged into https://github.com/NoRedInk/servant-ruby/tree/next-version

**Comment by jwoudenberg** [comment]
@stoeffel I think we still need this PR though, don't we? To update the generated code after changing the generation logic?

**Comment by stoeffel** [comment]
@jwoudenberg I don't understand? This code is now merged into the branch we currently track in stack.yml and I created a separate PR to the upstream repo.

**Comment by jwoudenberg** [comment]
Awesome, sorry for the noise!

**Pull request closed without merging**
